-- MySQL Script generated by MySQL Workbench
-- Tue Jun 28 11:56:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Linkinim
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Linkinim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Linkinim` DEFAULT CHARACTER SET utf8 ;
USE `Linkinim` ;

-- -----------------------------------------------------
-- Table `Linkinim`.`Utenti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`Utenti` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`Utenti` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(250) NOT NULL,
  `Cognome` VARCHAR(250) NOT NULL,
  `CodFisc` VARCHAR(16) NOT NULL,
  `DataDiNascita` DATE NOT NULL,
  `Email` VARCHAR(250) NOT NULL,
  `Password` VARCHAR(250) NOT NULL,
  `Matching` TINYINT NULL DEFAULT NULL,
  `ProfEsterno` TINYINT NULL DEFAULT NULL,
  `Iban` VARCHAR(27) NULL DEFAULT NULL,
  `ImmagineUrl` VARCHAR(250) NULL DEFAULT NULL,
  `DataAssunzione` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `CodFisc_UNIQUE` (`CodFisc` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`Post` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`Post` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Testo` VARCHAR(250) NULL DEFAULT NULL,
  `Datetime` DATETIME NULL DEFAULT NULL,
  `IdUtente` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdUtente_idx` (`IdUtente` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `IdUtente`
    FOREIGN KEY (`IdUtente`)
    REFERENCES `Linkinim`.`Utenti` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`CommentiPost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`CommentiPost` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`CommentiPost` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdUtente` INT NOT NULL,
  `Testo` VARCHAR(240) NOT NULL,
  `Datetime` DATETIME NOT NULL,
  `IdPost` INT NOT NULL,
  `IdCommento` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Iddipendente_idx` (`IdUtente` ASC) VISIBLE,
  INDEX `IdPost_idx` (`IdPost` ASC) VISIBLE,
  INDEX `IdCommento_idx` (`IdCommento` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `IdUtente`
    FOREIGN KEY (`IdUtente`)
    REFERENCES `Linkinim`.`Utenti` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdPost`
    FOREIGN KEY (`IdPost`)
    REFERENCES `Linkinim`.`Post` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdCommento`
    FOREIGN KEY (`IdCommento`)
    REFERENCES `Linkinim`.`CommentiPost` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`Corsi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`Corsi` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`Corsi` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdProf` INT NOT NULL,
  `Titolo` VARCHAR(250) NOT NULL,
  `Specializzazione` INT NOT NULL,
  `Durata` INT NOT NULL,
  `Capitoli` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdProf_idx` (`IdProf` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `IdProf`
    FOREIGN KEY (`IdProf`)
    REFERENCES `Linkinim`.`Utenti` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`CommentiCorsi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`CommentiCorsi` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`CommentiCorsi` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdUtente` INT NOT NULL,
  `Testo` VARCHAR(240) NULL DEFAULT NULL,
  `Datetime` DATETIME NOT NULL,
  `IdCorso` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Iddipendente_idx` (`IdUtente` ASC) VISIBLE,
  INDEX `IdCorso_idx` (`IdCorso` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `IdUtente`
    FOREIGN KEY (`IdUtente`)
    REFERENCES `Linkinim`.`Utenti` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdCorso`
    FOREIGN KEY (`IdCorso`)
    REFERENCES `Linkinim`.`Corsi` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`UtentiCorsi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`UtentiCorsi` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`UtentiCorsi` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdCorso` INT NOT NULL,
  `IdStudente` INT NOT NULL,
  `DataIscrizione` DATETIME NOT NULL,
  `CapitoloAttuale` INT NULL DEFAULT NULL,
  `Completato` TINYINT NULL DEFAULT NULL,
  `DataCompletamento` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdCorso_idx` (`IdCorso` ASC) VISIBLE,
  INDEX `IdStudente_idx` (`IdStudente` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `IdCorso`
    FOREIGN KEY (`IdCorso`)
    REFERENCES `Linkinim`.`Corsi` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdStudente`
    FOREIGN KEY (`IdStudente`)
    REFERENCES `Linkinim`.`Utenti` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`Settori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`Settori` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`Settori` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`Specializzazioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`Specializzazioni` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`Specializzazioni` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(250) NOT NULL,
  `IdSettore` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdSettore_idx` (`IdSettore` ASC) VISIBLE,
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `IdSettore`
    FOREIGN KEY (`IdSettore`)
    REFERENCES `Linkinim`.`Settori` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`CorsiSpecializzazioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`CorsiSpecializzazioni` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`CorsiSpecializzazioni` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdCorso` INT NOT NULL,
  `IdSpecializzazione` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdCorso_idx` (`IdCorso` ASC) VISIBLE,
  INDEX `IdSpecializzazione_idx` (`IdSpecializzazione` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `IdCorso`
    FOREIGN KEY (`IdCorso`)
    REFERENCES `Linkinim`.`Corsi` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdSpecializzazione`
    FOREIGN KEY (`IdSpecializzazione`)
    REFERENCES `Linkinim`.`Specializzazioni` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`UtentiSpecializzazioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`UtentiSpecializzazioni` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`UtentiSpecializzazioni` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdUtente` INT NOT NULL,
  `IdSpecializzazione` INT NOT NULL,
  `DataOttenimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdUtente_idx` (`IdUtente` ASC) VISIBLE,
  INDEX `IdSpecializzazione_idx` (`IdSpecializzazione` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `IdUtente`
    FOREIGN KEY (`IdUtente`)
    REFERENCES `Linkinim`.`Utenti` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdSpecializzazione`
    FOREIGN KEY (`IdSpecializzazione`)
    REFERENCES `Linkinim`.`Specializzazioni` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`Quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`Quiz` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`Quiz` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdCorso` INT NOT NULL,
  `IdCapitolo` INT NULL DEFAULT NULL,
  `RispostaCorretta` VARCHAR(250) NULL DEFAULT NULL,
  `RispostaErrata1` VARCHAR(250) NULL DEFAULT NULL,
  `RispostaErrata2` VARCHAR(250) NULL DEFAULT NULL,
  `RispostaErrata3` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IdCorso_idx` (`IdCorso` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `IdCorso`
    FOREIGN KEY (`IdCorso`)
    REFERENCES `Linkinim`.`Corsi` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linkinim`.`Token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Linkinim`.`Token` ;

CREATE TABLE IF NOT EXISTS `Linkinim`.`Token` (
  `Token` VARCHAR(250) NOT NULL,
  `IdUtente` INT NOT NULL,
  `Scadenza` BIGINT NOT NULL,
  `RemindMe` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Token`),
  INDEX `IdUtente_idx` (`IdUtente` ASC) VISIBLE,
  UNIQUE INDEX `Token_UNIQUE` (`Token` ASC) VISIBLE,
  CONSTRAINT `IdUtente`
    FOREIGN KEY (`IdUtente`)
    REFERENCES `Linkinim`.`Utenti` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
